[package]
name = "util"
version = "0.1.0"
authors = ["Seulgi Kim <dev@seulgi.kim>"]
edition = "2018"

[[bin]]
name = "commander"
path = "./src/commander.rs"

[dependencies]
common = { path = "../common" }
